name: Setup
description: "Setup the GitHub Actions environment with nix."

inputs:
  REPO_AUTH_TOKEN:
    description: "The GitHub repository authentication token."
    required: true

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v17
      with:
        # The action automatically adds max-jobs and experimental-features,
        # but we choose to keep them for those looking for an easy configuration
        # to copy-paste from.
        # Note that the action also adds trusted-users so we can access the binary
        # cache.
        extra_nix_config: |
          access-tokens = github.com=${{ inputs.REPO_AUTH_TOKEN }}
          experimental-features = nix-command flakes
          max-jobs = auto
          http-connections = 0
          substitute = true
          fallback = true
          keep-outputs = false
          keep-derivations = false
