name: Nix CI

on:
  - pull_request
  - push

jobs:
  macos-11:
    name: macos-11
    uses: ./.github/workflows/nix-ci-helper.yaml
    with:
      os-name: macos-11
      z3-tags: '["z3-4.11.0","z3-4.10.2","z3-4.10.1"]'
    secrets: inherit

  macos-12:
    name: macos-12
    uses: ./.github/workflows/nix-ci-helper.yaml
    with:
      os-name: macos-12
      z3-tags: '["z3-4.11.0","z3-4.10.2","z3-4.10.1"]'
    secrets: inherit

  ubuntu-20_04:
    name: ubuntu-20.04
    uses: ./.github/workflows/nix-ci-helper.yaml
    with:
      os-name: ubuntu-20.04
      z3-tags: '["z3-4.11.0","z3-4.10.2","z3-4.10.1"]'
    secrets: inherit

  ubuntu-22_04:
    name: ubuntu-22.04
    uses: ./.github/workflows/nix-ci-helper.yaml
    with:
      os-name: ubuntu-22.04
      z3-tags: '["z3-4.11.0","z3-4.10.2","z3-4.10.1"]'
    secrets: inherit
